#ifndef SYM_JAUNDICE_AND_OR_ASCITES
#define SYM_JAUNDICE_AND_OR_ASCITES
#include "../triage_level.h"
#include <stdbool.h>

enum Jaundice_and_or_ascites_pain_kids_older_than_2mth_and_younger_than_5yrs { JAOAPKOTAYT_FLACC_8_to_10, JAOAPKOTAYT_FLACC_4_to_7, JAOAPKOTAYT_FLACC_0_to_3 };
enum Jaundice_and_or_ascites_pain_kids_younger_than_2mth { JAOAPKYT_NIPS_4_to_6, JAOAPKYT_NIPS_1_to_3, JAOAPKYT_NIPS_0 };
enum Jaundice_and_or_ascites_pain_adult_or_kids_5yr_or_older { JAOAPAOKOO_NRS_VAS_4_to_10_and_one_or_more_of_yellow_VP_painful_movementpatterns_affected_regular_condition, JAOAPAOKOO_NRS_VAS_4_to_10_and_green_VP_free_and_natural_movementpatterns_non_affected_regular_condition, JAOAPAOKOO_NRS_VAS_0_to_3_and_green_VP_free_and_natural_movementpatterns_non_affected_regular_condition };
enum Jaundice_and_or_ascites_morphine_within_120min_before_arrival { JAOAMWBA_yellow_pain_evaluation, JAOAMWBA_green_pain_evaluation };


struct Jaundice_and_or_ascites {
    enum Jaundice_and_or_ascites_pain_kids_older_than_2mth_and_younger_than_5yrs pain_kids_older_than_2mth_and_younger_than_5yrs;
    enum Jaundice_and_or_ascites_pain_kids_younger_than_2mth pain_kids_younger_than_2mth;
    bool Jaundice_and_or_ascites_newly_arisen_confusion;
    bool Jaundice_and_or_ascites_suspected_infection;
    bool Jaundice_and_or_ascites_risk_patient;
    enum Jaundice_and_or_ascites_pain_adult_or_kids_5yr_or_older pain_adult_or_kids_5yr_or_older;
    enum Jaundice_and_or_ascites_morphine_within_120min_before_arrival morphine_within_120min_before_arrival;
};

enum Triage_Level get_symptoms_jaundice_and_or_ascites_triage(struct Jaundice_and_or_ascites jaundice_and_or_ascites);

#endif
